spring.application.name=journal-db
server.port=7000

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=journaldb
# spring.mongodb.password=password

# spring.mongodb.uri=mongodb+srv://rt5222630_db_user:eIi9TPAuj8yhWKDw@cluster0.jwzo3wh.mongodb.net/journal-db

# it is used for creating unique values as like { unique: true } in mongoose in node.js
spring.data.mongodb.auto-index-creation=true